language: d
sudo: false

matrix:
  include:
    - d: dmd-2.083.0
    # - d: dmd-2.082.1
    # - d: dmd-2.081.2
    # - d: ldc-1.12.0
    # - d: ldc-1.11.0
    # - d: ldc-1.10.0

script:
  - ./install.sh
  - export PATH=$PATH:dpp/bin
  - ./ci.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
